# Generated by Django 2.0.7 on 2018-08-13 17:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('badge', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('forecast_url', models.URLField()),
                ('one_day', models.PositiveSmallIntegerField(null=True)),
                ('three_day', models.PositiveSmallIntegerField(null=True)),
                ('six_day', models.PositiveSmallIntegerField(null=True)),
                ('one_day_r', models.PositiveSmallIntegerField(null=True)),
                ('three_day_r', models.PositiveSmallIntegerField(null=True)),
                ('six_day_r', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('duration', models.DurationField(null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('attributes', models.ManyToManyField(blank=True, to='quickstart.Attribute')),
                ('forecasts', models.ManyToManyField(blank=True, to='quickstart.Forecast')),
            ],
        ),
    ]
