# Generated by Django 2.0.7 on 2018-08-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='latitude',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='longitude',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='forecast_url',
            field=models.URLField(null=True),
        ),
    ]
