# Generated by Django 2.0.7 on 2018-08-08 06:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20180807_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('badge', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='trips',
            field=models.ManyToManyField(to='quickstart.Trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='attributes',
            field=models.ManyToManyField(to='quickstart.Attribute'),
        ),
    ]
