# Generated by Django 2.0.7 on 2018-08-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20180808_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='trips',
        ),
        migrations.AddField(
            model_name='forecast',
            name='forecast_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='quickstart.Attribute'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='forecasts',
            field=models.ManyToManyField(blank=True, to='quickstart.Forecast'),
        ),
    ]
