# Generated by Django 2.0.7 on 2018-08-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_auto_20180808_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='forecast_url',
        ),
        migrations.AlterField(
            model_name='forecast',
            name='forecast_url',
            field=models.URLField(primary_key=True, serialize=False),
        ),
    ]
