# Generated by Django 2.0.7 on 2018-08-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_auto_20180808_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='forecast_url',
            field=models.URLField(),
        ),
    ]
