# Generated by Django 2.0.7 on 2018-08-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_auto_20180808_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='one_day',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='one_day_r',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='six_day',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='six_day_r',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='three_day',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='three_day_r',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
